import "server-only";

import { isTestEnvironment } from "@/lib/constants";
import { inMemoryQueries } from "./in-memory";
import {
  createCustomModel as pgCreateCustomModel,
  createCustomModels as pgCreateCustomModels,
  createCustomProvider as pgCreateCustomProvider,
  createStreamId as pgCreateStreamId,
  createUserFromClerk as pgCreateUserFromClerk,
  deleteAllChatsByUserId as pgDeleteAllChatsByUserId,
  deleteChatById as pgDeleteChatById,
  deleteCustomModel as pgDeleteCustomModel,
  deleteCustomProvider as pgDeleteCustomProvider,
  deleteDocumentsByIdAfterTimestamp as pgDeleteDocumentsByIdAfterTimestamp,
  deleteMessagesByChatIdAfterTimestamp as pgDeleteMessagesByChatIdAfterTimestamp,
  deleteToolConfig as pgDeleteToolConfig,
  getAllChatsByUserId as pgGetAllChatsByUserId,
  getAllMessagesByUserId as pgGetAllMessagesByUserId,
  getCatalogSync as pgGetCatalogSync,
  getChatById as pgGetChatById,
  getChatsByUserId as pgGetChatsByUserId,
  getCustomModelsByProviderId as pgGetCustomModelsByProviderId,
  getCustomModelsByProviderIds as pgGetCustomModelsByProviderIds,
  getCustomModelsForUser as pgGetCustomModelsForUser,
  getCustomProviderById as pgGetCustomProviderById,
  getCustomProviderByModelId as pgGetCustomProviderByModelId,
  getCustomProvidersByUserId as pgGetCustomProvidersByUserId,
  getDecryptedApiKey as pgGetDecryptedApiKey,
  getDocumentById as pgGetDocumentById,
  getDocumentsById as pgGetDocumentsById,
  getMessageById as pgGetMessageById,
  getMessageCountByUserId as pgGetMessageCountByUserId,
  getMessagesByChatId as pgGetMessagesByChatId,
  getOrCreateUserByEmail as pgGetOrCreateUserByEmail,
  getStreamIdsByChatId as pgGetStreamIdsByChatId,
  getSuggestionsByDocumentId as pgGetSuggestionsByDocumentId,
  getToolConfigByUserId as pgGetToolConfigByUserId,
  getToolConfigsByUserId as pgGetToolConfigsByUserId,
  getUserByClerkId as pgGetUserByClerkId,
  getUserSettings as pgGetUserSettings,
  saveChat as pgSaveChat,
  saveDocument as pgSaveDocument,
  saveMessages as pgSaveMessages,
  saveSuggestions as pgSaveSuggestions,
  updateCatalogSync as pgUpdateCatalogSync,
  updateChatTitleById as pgUpdateChatTitleById,
  updateChatVisibilityById as pgUpdateChatVisibilityById,
  updateCustomModel as pgUpdateCustomModel,
  updateCustomProvider as pgUpdateCustomProvider,
  updateDocumentContent as pgUpdateDocumentContent,
  updateMessage as pgUpdateMessage,
  upsertToolConfig as pgUpsertToolConfig,
  upsertUserSettings as pgUpsertUserSettings,
} from "./queries.pg";

const pgQueries = {
  createCustomModel: pgCreateCustomModel,
  createCustomModels: pgCreateCustomModels,
  createCustomProvider: pgCreateCustomProvider,
  createStreamId: pgCreateStreamId,
  createUserFromClerk: pgCreateUserFromClerk,
  deleteAllChatsByUserId: pgDeleteAllChatsByUserId,
  deleteChatById: pgDeleteChatById,
  deleteCustomModel: pgDeleteCustomModel,
  deleteCustomProvider: pgDeleteCustomProvider,
  deleteDocumentsByIdAfterTimestamp: pgDeleteDocumentsByIdAfterTimestamp,
  deleteMessagesByChatIdAfterTimestamp: pgDeleteMessagesByChatIdAfterTimestamp,
  deleteToolConfig: pgDeleteToolConfig,
  getAllChatsByUserId: pgGetAllChatsByUserId,
  getAllMessagesByUserId: pgGetAllMessagesByUserId,
  getCatalogSync: pgGetCatalogSync,
  getChatById: pgGetChatById,
  getChatsByUserId: pgGetChatsByUserId,
  getCustomModelsByProviderId: pgGetCustomModelsByProviderId,
  getCustomModelsByProviderIds: pgGetCustomModelsByProviderIds,
  getCustomModelsForUser: pgGetCustomModelsForUser,
  getCustomProviderById: pgGetCustomProviderById,
  getCustomProviderByModelId: pgGetCustomProviderByModelId,
  getCustomProvidersByUserId: pgGetCustomProvidersByUserId,
  getDecryptedApiKey: pgGetDecryptedApiKey,
  getDocumentById: pgGetDocumentById,
  getDocumentsById: pgGetDocumentsById,
  getMessageById: pgGetMessageById,
  getMessageCountByUserId: pgGetMessageCountByUserId,
  getMessagesByChatId: pgGetMessagesByChatId,
  getOrCreateUserByEmail: pgGetOrCreateUserByEmail,
  getStreamIdsByChatId: pgGetStreamIdsByChatId,
  getSuggestionsByDocumentId: pgGetSuggestionsByDocumentId,
  getToolConfigByUserId: pgGetToolConfigByUserId,
  getToolConfigsByUserId: pgGetToolConfigsByUserId,
  getUserByClerkId: pgGetUserByClerkId,
  getUserSettings: pgGetUserSettings,
  saveChat: pgSaveChat,
  saveDocument: pgSaveDocument,
  saveMessages: pgSaveMessages,
  saveSuggestions: pgSaveSuggestions,
  updateCatalogSync: pgUpdateCatalogSync,
  updateChatTitleById: pgUpdateChatTitleById,
  updateChatVisibilityById: pgUpdateChatVisibilityById,
  updateCustomModel: pgUpdateCustomModel,
  updateCustomProvider: pgUpdateCustomProvider,
  updateDocumentContent: pgUpdateDocumentContent,
  updateMessage: pgUpdateMessage,
  upsertToolConfig: pgUpsertToolConfig,
  upsertUserSettings: pgUpsertUserSettings,
};

type Queries = typeof pgQueries;

const memQueries = inMemoryQueries as unknown as Queries satisfies Queries;

const impl: Queries = isTestEnvironment ? memQueries : pgQueries;

export const {
  createCustomModel,
  createCustomModels,
  createCustomProvider,
  createStreamId,
  createUserFromClerk,
  deleteAllChatsByUserId,
  deleteChatById,
  deleteCustomModel,
  deleteCustomProvider,
  deleteDocumentsByIdAfterTimestamp,
  deleteMessagesByChatIdAfterTimestamp,
  getAllChatsByUserId,
  getAllMessagesByUserId,
  getChatById,
  getChatsByUserId,
  getCatalogSync,
  getCustomModelsByProviderId,
  getCustomModelsByProviderIds,
  getCustomModelsForUser,
  getCustomProviderById,
  getCustomProviderByModelId,
  getCustomProvidersByUserId,
  getDecryptedApiKey,
  getDocumentById,
  getDocumentsById,
  getMessageById,
  getMessageCountByUserId,
  getMessagesByChatId,
  getOrCreateUserByEmail,
  getStreamIdsByChatId,
  getSuggestionsByDocumentId,
  getToolConfigByUserId,
  getToolConfigsByUserId,
  getUserByClerkId,
  getUserSettings,
  saveChat,
  saveDocument,
  saveMessages,
  saveSuggestions,
  updateChatTitleById,
  updateChatVisibilityById,
  updateCatalogSync,
  updateCustomModel,
  updateCustomProvider,
  updateDocumentContent,
  updateMessage,
  deleteToolConfig,
  upsertToolConfig,
  upsertUserSettings,
} = impl;
